services:
  - type: web
    name: govno-drop-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: ADMIN_IDS
        value: "8080874290"
      - key: PYTHON_VERSION
        value: "3.11.9"
